### ISSUE TITLE
Typo3 6.2 compatibility

### ISSUE THREAD

**Issue by falkoneven** [TYPO3-Solr/ext-solrmlt#1]
Good morning,

I have installed the last version on my 6.2 typo3 website yet I get the following error when I place the plugin on a page:

Fatal error: Class 'tx_solr_pi_mlt' not found in /var/www/html/eukn.dev.alternet.nl/typo3_src-6.2.10/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4439

Could you keep me posted on when this issue will be fixed? 

Thanks in regard.

Falko Neven
falko@alternet.nl
AlterNET

**Comment by dkd-friedrich** [comment]
Hello Falko Neven,

unfortunately I couldn't reproduce this error, I placed the plugin "Search: More Like this" on a page
"Add new record .." => "General Plugin" => "Selected Plugin" => "Search: More Like this".

But I got no error and the frontend is working too (TYPO3 6.2.12). Do you have further details?

Best regards

Markus Friedrich

**Comment by falkoneven** [comment]
Good afternoon,

Details:
- Solrmlt 1.0.1
- TYPO3 6.2.10
- PHP 5.4.36

Im not sure what other details could be interesting to resolve this issue. 
Please let me know if you need additional details.

Thanks in regard,

Falko Neven
falko@alternet.nl
AlterNET

**Comment by dkd-friedrich** [comment]
Caching issue, from my point of view. Clearing the caches (typo3temp/Cache) should solve this issue
