### ISSUE TITLE
Create a release of solrmlt 1.1.0

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solrmlt#3]
We should create a Github and TER Release of solrmlt 1.1.0

**Comment by dkd-janke** [comment]
+1

**Comment by irnnr** [comment]
We'll have to fix #4 first IMO

**Comment by irnnr** [comment]
I have set up a milestone to keep track of open issues: 
https://github.com/TYPO3-Solr/ext-solrmlt/milestones/1.1.0

**Comment by irnnr** [comment]
I'll review the code and add more as I find them. There should not be too much left beside #4 however, but that one should be fixed. The extension is small and does not do that much, so if we do a release it should be complete.
