### ISSUE TITLE
Check with TYPO3 6.2

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solrmlt#6]
Check if the extension is running and fix if not :)

**Comment by timohund** [comment]
I've checked the master with TYPO3 6.2 and everything worked (expected the flexform issue, but this effected both versions)

**Comment by irnnr** [comment]
ok. I don't think the error I got was specifically related to solrmlt. It was just weird the whole installation fell apart when updating to 6.2.16
